# Generated by Django 4.0.3 on 2022-03-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arcticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbb_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('bbb_text', models.TextField(verbose_name='Текст статьи')),
                ('bbb_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=55, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=150, verbose_name='Текст комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.arcticle')),
            ],
        ),
    ]
